# Generated by Django 4.2.7 on 2023-11-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestsGUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(default=654, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
